version: 2

jobs:
  test:

    macos:
      xcode: "9.0"

    docker:
      - image: circleci/ruby:2.4.1-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-{{ .Branch }}

      - run: 
          name: Bundler
          command: bundle install --path vendor/bundle

      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install --verbose

      - save_cache:
          key: v2-{{ .Branch }}
          paths:
            - Pods
            - vendor/bundle

      - run:
          name: Test
          command: bundle exec fastlane test

workflows:
  version: 2
  test:
    jobs:
      - test
