version: 2

jobs:
  test:

    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Setup
          command: bundle exec fastlane setup

      - run:
          name: Test
          command: bundle exec fastlane test

workflows:
  version: 2
  test:
    jobs:
      - test
