version: 2

jobs:
  test:

    macos:
      xcode: "9.0"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-{{ .Branch }}

      - run: 
          name: Bundler
          command: bundle install --path vendor/bundle

      - run:
          name: Setup
          command: bundle exec fastlane setup

      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - Carthage
            - vendor/bundle

      - run:
          name: Test
          command: bundle exec fastlane test
