fastlane_version "2.26.1"

default_platform :ios

platform :ios do

  before_all do
    Dir.chdir("..") do
      # code here runs in the parent directory
      sh "scripts/update_carthage"
    end    
  end

  lane :setup do
    puts "Done"
  end

  lane :test do
    scan
  end

  lane :beta do |options|
    increment_build_number(build_number: options[:build_number])
    match(type: "appstore")
    gym
    pilot(skip_waiting_for_build_processing: true)
  end
end
