fastlane_version "2.26.1"

default_platform :ios

platform :ios do

  lane :test do
    scan
  end

  lane :beta do |options|
    increment_build_number(build_number: options[:build_number])
    match(type: "appstore")
    gym
    pilot(skip_waiting_for_build_processing: true)
  end
end
