#!/bin/sh

# Build Carthage
# Checks the Cartfile.resolved vs. the local built dependencies
# If not satisified, builds and saves the new Cartfile.resolved
if ! cmp -s Cartfile.resolved Carthage/Cartfile.resolved; then
  echo "Building Carthage Dependencies"
  carthage bootstrap --platform iOS
  cp Cartfile.resolved Carthage
else
  echo "Carthage Dependencies Satisfied"
fi

